services:
  redis:
    image: redis:7-alpine
    container_name: redis-local
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - portfolio
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: portfolio-backend
    container_name: portfolio-backend-local
    env_file:
      - ./.env.local
    ports:
      - "3000:3000"
    networks:
      - portfolio
    depends_on:
      - redis
    volumes:
      - ./backend:/usr/src/app
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: portfolio-frontend
    container_name: portfolio-frontend-local
    env_file:
      - ./.env.local
    ports:
      - "3001:3001"
    volumes:
      - ./frontend:/usr/src/app
    networks:
      - portfolio
    depends_on:
      - backend

volumes:
  redis-data:
    driver: local

networks:
  portfolio:
    driver: bridge
