services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: portfolio-backend
    container_name: portfolio-backend-prod
    ports:
      - "3000:3000"
    restart: unless-stopped
