services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - ENV=$ENV
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - BACKEND_PORT=$BACKEND_PORT
      - BACKEND_GROQ_API_KEY=$BACKEND_GROQ_API_KEY
      - BACKEND_GROQ_API_URL=$BACKEND_GROQ_API_URL
    image: portfolio-backend
    container_name: portfolio-backend-prod
    ports:
      - "3000:3000"
    networks:
      - portfolio
    volumes:
      - ./backend:/usr/src/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_BACKEND_URL
        - VITE_BASE_URL
        - VITE_PORT
        - VITE_MAX_CHAT_HISTORY_LIMIT
        - VITE_MAX_CHAT_CHARACTERS

    image: portfolio-frontend
    container_name: portfolio-frontend-prod
    ports:
      - "3001:3001"
    volumes:
      - ./frontend:/usr/src/app
    networks:
      - portfolio
    depends_on:
      - backend
networks:
  portfolio:
    driver: bridge
