services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: portfolio-backend
    container_name: portfolio-backend-prod
    ports:
      - "3000:3000"
    networks:
      - portfolio
    volumes:
      - ./backend:/usr/src/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_BACKEND_URL: ${VITE_BACKEND_URL}
        VITE_BASE_URL: ${VITE_BASE_URL}
        VITE_PORT: ${VITE_PORT}
    image: portfolio-frontend
    container_name: portfolio-frontend-prod
    ports:
      - "3001:3001"
    volumes:
      - ./frontend:/usr/src/app
    networks:
      - portfolio
    depends_on:
      - backend
networks:
  portfolio:
    driver: bridge
